* blog

This is a blog (template) with:
- all posts loaded into the artifact (i.e. no refresh when switching between posts)
- fuzzy search over all the post content + titles
- posts written directly in ClojureScript (with help of macros) for extensibility
** running stuff
- run =yarn install=
- repl: =clj -X:cljs=
  - then run =cider-jack-clj&cljs=
- make a post: create =src/kev/blog/posts/mypost.cljs= (must be in that subdir).
- build: =clj -X:cljs:build=. will produce artifact in /docs/js
- test the build artifact by using =python3 -m http.server= inside of the /docs directory.
  Must change index.html since this is expected to be run at /blog path with gh pages
** impl
- I want it to be like https://project-serum.github.io/anchor/getting-started/introduction.html
  (slide the width of the page back and forth and see how it scales!)
*** todo
- [x] build fn. Add a blog post, run this, and it will do everything and post it even
- [x] search. - maybe https://fusejs.io/
  - no. [[https://github.com/farzher/fuzzysort][fuzzysort]] was better.
  - I also implemented a custom solution on top where I chop up the text of all
    the posts into bits, search over those bits and display the bits w/ text around
    them and it turned out nice
